name: products_printer
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.0.10+1
  sqflite: ^2.4.2+1
  path: ^1.9.1
  mobile_scanner: ^7.2.0
  get_it: ^9.2.1
  equatable: ^2.0.8
  intl: ^0.20.2
  shimmer: ^3.0.0
  excel: ^4.0.0
  file_picker: ^11.0.1
  share_plus: ^12.0.2
  path_provider: ^2.1.5
  lucide_icons_flutter: ^1.0.0
  gap: ^3.0.1
  image_picker: ^1.2.2
  pdf: ^3.11.3
  printing: ^5.14.0
  easy_localization: ^3.0.8
  lottie: ^3.3.0
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^10.0.0
  permission_handler: ^12.0.1
  image: ^4.3.0
  audioplayers: ^6.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/lottie/
    - assets/svg/

  fonts:
    - family: Alex
      fonts:
        - asset: assets/fonts/Alex/Alex-Regular.ttf
        - asset: assets/fonts/Alex/Alex-Light.ttf
          weight: 300
        - asset: assets/fonts/Alex/Alex-Medium.ttf
          weight: 500
        - asset: assets/fonts/Alex/Alex-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Alex/Alex-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700


# dart run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    color: "#ffffff"

# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/images/android-luancher-icon.png"
  image_path_ios: "assets/images/ios-luancher-icon.png"


